Repository JuanDBta/booking-bites, pull requests merged in 2023-10, with the labels that each got.

#14 Database migration
  app/models/reservation.rb
  app/models/restaurant.rb
  app/models/section.rb
  app/models/user.rb
  config/database.yml
  db/migrate/20231019144827_create_users.rb
  db/migrate/20231019145001_create_restaurants.rb
  db/migrate/20231019145350_create_sections.rb
  db/migrate/20231019150445_create_reservations.rb
  db/schema.rb
  test/fixtures/reservations.yml
  test/fixtures/restaurants.yml
  test/fixtures/sections.yml
  test/fixtures/users.yml
  test/models/reservation_test.rb
  test/models/restaurant_test.rb
  test/models/section_test.rb
  test/models/user_test.rb
Labels: DATABASE

#15 Reservations controller
  app/controllers/reservations_controller.rb
  app/helpers/reservations_helper.rb
  config/database.yml
  config/routes.rb
  test/controllers/reservations_controller_test.rb
Labels: BACK END

#21 Reservations page
  README.md
  app/assets/stylesheets/application.css
  app/assets/stylesheets/delete.css
  app/assets/stylesheets/main.css
  app/assets/stylesheets/navbar.css
  app/assets/stylesheets/reservations.css
  app/assets/stylesheets/sectionnew.css
  app/javascript/components/Delete.js
  app/javascript/components/ReservationCreate.js
  app/javascript/components/ReservationNew.js
  app/javascript/components/Reservations.js
  app/javascript/components/SectionNew.js
  app/javascript/redux/features/reservations/reservationSlice.js
  app/javascript/redux/features/reservations/reservationsApiSlice.js
  app/javascript/redux/store.js
Labels: FRONT END
